---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code
    restart: unless-stopped
    env_file:
      - /mnt/cpool/code/.env
      - /mnt/cpool/code/.env.secrets
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-568}
      - TZ=Europe/Paris
      - PASSWORD=${CODE_PASSWORD}
    volumes:
      - /mnt/cpool/nginx/:/nginx
      - /mnt/cpool/code/:/code-server
      - /mnt/cpool/drawio/:/drawio
      - /mnt/cpool/compose/:/compose
      - /mnt/cpool/traefik/:/traefik
      - /mnt/cpool/prometheus/:/prometheus
      - /mnt/cpool/grafana/:/grafana         
      - /mnt/cpool/litellm/:/litellm         
      - /mnt/cpool/code/config:/config
      - /mnt/cpool/compose/nabla-compose/:/config/workspace
    ports:
      - 8443:8443
    security_opt:
      - apparmor=unconfined
