---
configs:
  poll-config.yml:
    content: |
      - url: https://github.com/albandrieu/nabla-compose.git
        reference: main
        interval: 3600

# https://doco.cd/latest/External-Secrets/
secrets:
  1pw_token:
    # file: /root/.doco-cd/1pw_token
    file: /mnt/cpool/home/albandrieu/.doco-cd/1pw_token

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    user: "568:568" # TrueNAS apps user
    environment:
      DOMAIN: "https://vaultwarden.albandrieu.com"
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
      WEBSOCKET_ENABLED: "true"
      ADMIN_TOKEN: "${VAULTWARDEN_ADMIN_TOKEN}"
    volumes:
      # - ./vw-data/:/data/
      - /mnt/cpool/vaultwarden/vw-data/:/data/
    ports:
      - 30032:80

  bitwarden-api:
    image: ghcr.io/kimdre/bitwarden-rest-api-server:latest
    restart: unless-stopped
    user: "568:568" # TrueNAS apps user
    environment:
      BW_HOST: "https://vaultwarden.albandrieu.com"
      BW_CLIENTID: "${BW_CLIENTID}"
      BW_CLIENTSECRET: "${BW_CLIENTSECRET}"
      BW_PASSWORD: "${BW_PASSWORD}"
    volumes:
      - /mnt/cpool/vaultwarden/bw-data/:/data/      
    expose:
      - "8087"
    depends_on:
      - vaultwarden
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8087/status >/dev/null 2>&1 || wget -qO- http://127.0.0.1:8087/list/object/items >/dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
