#!/usr/bin/env bash
set -euo pipefail

MODE="${1:---check}"
CANONICAL_ROOT="${CYBERBRO_CANONICAL_ROOT:-/mnt/cpool/compose/nabla-compose}"
RUNTIME_DIR="${CYBERBRO_RUNTIME_DIR:-/mnt/cpool/secrets/runtime/cyberbro}"
ENV_FILE="${CYBERBRO_ENV_FILE:-${RUNTIME_DIR}/.env}"
SECRETS_FILE="${CYBERBRO_SECRETS_FILE:-${RUNTIME_DIR}/.env.secrets}"

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

case "${MODE}" in
  --check | --apply) ;;
  *) fail "usage: $0 [--check|--apply]" ;;
esac

[[ "${EUID}" -eq 0 ]] || fail "run with sudo -E so canonical runtime files remain root-only"
for command in git install mktemp stat python3 grep; do
  command -v "${command}" >/dev/null 2>&1 || fail "${command} is required"
done

ROOT="$(git rev-parse --show-toplevel)"
[[ "${ROOT}" == "${CANONICAL_ROOT}" ]] ||
  fail "run from canonical TrueNAS checkout ${CANONICAL_ROOT}; current checkout is ${ROOT}"
cd "${CANONICAL_ROOT}"

write_runtime_env() {
  local tmp
  tmp="$(mktemp)"
  trap 'rm -f "${tmp}"' RETURN
  cat >"${tmp}" <<ENV
# Generated by scripts/truenas/bootstrap-cyberbro-env.sh
# Non-secret Cyberbro runtime configuration.
API_CACHE_TIMEOUT=${CYBERBRO_API_CACHE_TIMEOUT:-86400}
API_PREFIX=${CYBERBRO_API_PREFIX:-api}
CROWDSTRIKE_FALCON_BASE_URL=${CYBERBRO_CROWDSTRIKE_FALCON_BASE_URL:-https://falcon.crowdstrike.com}
DFIR_IRIS_URL=${CYBERBRO_DFIR_IRIS_URL:-}
DISABLE_VERSION_CHECK=${CYBERBRO_DISABLE_VERSION_CHECK:-false}
GUI_CACHE_TIMEOUT=${CYBERBRO_GUI_CACHE_TIMEOUT:-1800}
GUI_ENABLED_ENGINES=${CYBERBRO_GUI_ENABLED_ENGINES:-}
GUNICORN_THREADS_COUNT=${CYBERBRO_GUNICORN_THREADS_COUNT:-1}
GUNICORN_TIMEOUT=${CYBERBRO_GUNICORN_TIMEOUT:-120}
GUNICORN_WORKERS_COUNT=${CYBERBRO_GUNICORN_WORKERS_COUNT:-1}
HISTER_BASE_URL=${CYBERBRO_HISTER_BASE_URL:-}
MAX_FORM_MEMORY_SIZE=${CYBERBRO_MAX_FORM_MEMORY_SIZE:-1048576}
MISP_FEEDBACK_SERVER_URL=${CYBERBRO_MISP_FEEDBACK_SERVER_URL:-}
MISP_URL=${CYBERBRO_MISP_URL:-}
OPENCTI_URL=${CYBERBRO_OPENCTI_URL:-}
RL_ANALYZE_URL=${CYBERBRO_RL_ANALYZE_URL:-}
SSL_VERIFY=${CYBERBRO_SSL_VERIFY:-true}
ENV
  install -o root -g root -m 600 "${tmp}" "${ENV_FILE}"
}

write_optional_secret_contract() {
  local tmp
  tmp="$(mktemp)"
  trap 'rm -f "${tmp}"' RETURN
  cat >"${tmp}" <<'ENV'
# Generated by scripts/truenas/bootstrap-cyberbro-env.sh
# Optional provider credentials. Empty values disable the corresponding engines.
ABUSEIPDB=
ALIENVAULT=
CRIMINALIP_API_KEY=
CROWDSTRIKE_CLIENT_ID=
CROWDSTRIKE_CLIENT_SECRET=
DFIR_IRIS_API_KEY=
GOOGLE_CSE_CX=
GOOGLE_CSE_KEY=
GOOGLE_SAFE_BROWSING=
HISTER_TOKEN=
IPAPI=
IPINFO=
MDE_CLIENT_ID=
MDE_CLIENT_SECRET=
MDE_TENANT_ID=
MISP_API_KEY=
MISP_FEEDBACK_TOKEN=
OPENCTI_API_KEY=
PROXY_URL=
RANSOMWARE_LIVE_API_KEY=
RL_ANALYZE_API_KEY=
ROSTI_API_KEY=
SHODAN=
SPUR_US=
THREATFOX=
VIRUSTOTAL=
WEBSCOUT=
ENV
  install -o root -g root -m 600 "${tmp}" "${SECRETS_FILE}"
}

render_vaultwarden_secrets() {
  local tmp
  tmp="$(mktemp)"
  trap 'rm -f "${tmp}"' RETURN
  python3 scripts/secrets/render_from_bitwarden.py \
    --app cyberbro \
    --output-file "${tmp}" || return 1
  [[ -s "${tmp}" ]] || return 1
  install -o root -g root -m 600 "${tmp}" "${SECRETS_FILE}"
}

verify_file() {
  local path="$1" label="$2"
  [[ -f "${path}" ]] || fail "missing ${label}: ${path}"
  [[ "$(stat -c '%U:%G %a' "${path}")" == "root:root 600" ]] ||
    fail "${path} must be root:root mode 0600"
}

if [[ "${MODE}" == "--apply" ]]; then
  install -d -o root -g root -m 700 "${RUNTIME_DIR}"
  write_runtime_env

  if [[ -n "${BW_SESSION:-}" ]] && command -v bw >/dev/null 2>&1; then
    if ! render_vaultwarden_secrets; then
      printf 'WARNING: Vaultwarden Cyberbro item is unavailable or incomplete; using the explicit optional-provider baseline.\n' >&2
      write_optional_secret_contract
    fi
  elif [[ ! -s "${SECRETS_FILE}" ]]; then
    printf 'WARNING: BW_SESSION/bw unavailable; using the explicit optional-provider baseline.\n' >&2
    write_optional_secret_contract
  fi
fi

verify_file "${ENV_FILE}" "Cyberbro runtime env file"
verify_file "${SECRETS_FILE}" "Cyberbro runtime secret file"
grep -Eq '^API_PREFIX=.+$' "${ENV_FILE}" || fail "${ENV_FILE} must define API_PREFIX"
grep -Eq '^SSL_VERIFY=(true|false)$' "${ENV_FILE}" || fail "${ENV_FILE} must define SSL_VERIFY=true|false"
grep -q '^VIRUSTOTAL=' "${SECRETS_FILE}" || fail "${SECRETS_FILE} does not match the Cyberbro provider contract"

printf 'OK: Cyberbro runtime env materialized: %s\n' "${ENV_FILE}"
printf 'OK: Cyberbro provider secret contract materialized: %s\n' "${SECRETS_FILE}"
