{
 "title": "pfSense System",
 "description": "Displays visualizations for system metrics.",
 "tags": [
  "pfsense",
  "pfrest",
  "networking"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(pfsense_system_memory_usage_ratio,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature (Celsius)",
   "type": "stat",
   "description": "Displays the system's current temperature in Celsius. Note not all systems support temperature readings.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_system_temperature_celsius{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Displays the percentage of CPU currently utilized by the system. Please note the algorithm used to determine this number is not 100% accurate. It is recommended to use values from the node-exporter instead.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_system_cpu_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{host }}"
    }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "timeseries",
   "description": "Displays the percentage of CPU usage over time. Please note the algorithm used to determine this number is not 100% accurate. It is recommended to use values from the node-exporter instead.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pfsense_system_cpu_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Displays the percentage of memory currently utilized by the system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_system_memory_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{host }}"
    }
   ]
  },
  {
   "title": "Memory Usage Over Time",
   "type": "timeseries",
   "description": "Displays the percentage of memory usage over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pfsense_system_memory_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "description": "Displays the system's current disk utilization as a percentage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_system_disk_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{host }}"
    }
   ]
  },
  {
   "title": "Disk Usage Over Time",
   "type": "timeseries",
   "description": "Displays the percentage of disk usage over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pfsense_system_disk_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "MBUF Usage",
   "type": "gauge",
   "description": "Displays the system's current MBUF utilization as a percentage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_system_mbuf_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{host }}"
    }
   ]
  },
  {
   "title": "MBUF Usage Over Time",
   "type": "timeseries",
   "description": "Displays the percentage of MBUF usage over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pfsense_system_mbuf_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "SWAP Usage",
   "type": "gauge",
   "description": "Displays the system's current SWAP utilization as a percentage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_system_swap_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{host }}"
    }
   ]
  },
  {
   "title": "SWAP Usage Over Time",
   "type": "timeseries",
   "description": "Displays the percentage of SWAP usage over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pfsense_system_swap_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}