{
 "title": "pfSense Firewall",
 "description": "Displays visualizations for firewall metrics.",
 "tags": [
  "pfsense",
  "pfrest",
  "networking"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(pfsense_firewall_states_usage_ratio,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Firewall States Usage",
   "type": "gauge",
   "description": "Displays the percentage of firewall states utilized in the firewall states table.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_firewall_states_usage_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Firewall States Count",
   "type": "stat",
   "description": "Displays the current number of firewall states registered in the firewall states table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_firewall_states_current_count{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Firewall States Remaining",
   "type": "stat",
   "description": "Displays the number of unused firewall state slots available to the firewall.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_firewall_states_maximum_count{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"} - pfsense_firewall_states_current_count{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}