# https://github.com/ntop/docker-ntop
services:
  nprobe_collector:
    image: ntop/nprobe:latest
    restart: always
    network_mode: "host"
    volumes:
      - /etc/nprobe.license:/etc/nprobe.license:ro
    command:
      [
        "nprobe",
        "--zmq",
        '"tcp://ntopng:5556"',
        "--interface",
        "none",
        "-n",
        "none",
        "--collector-port",
        "2055",
        "-T",
        '"@NTOPNG@"',
        "--collector-passthrough",
      ]

  ntopng:
    image: ntop/ntopng:latest
    restart: always
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN # Required for capturing packets and setting interfaces up
    volumes:
      - /etc/ntopng.license:/etc/ntopng.license:ro
    command: [
        "--interface",
        "tcp://*:5556c",
        "-w",
        "4000",
        "-F",
        "clickhouse",
        "--disable-login",
        "--local-networks",
        "172.17.0.57/24",
        "--community",
        "--dns-mode",
        "1",
        "--geoip-dir",
        "/usr/share/GeoIP",
        # "--redis 127.0.0.1:6379"
      ] # , '--insecure']
    environment:
      # - TZ=${TZ}
      - TZ=Europe/Paris
      - LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0} # Listen for connections on all interfaces
    depends_on:
      - clickhouse
      - nprobe_collector

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    network_mode: "host"
    restart: always
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server/

volumes:
  clickhouse_data:
  clickhouse_logs:
