---
# kics-scan ignore
services:
  # https://github.com/githubexporter/github-exporter
  github-exporter:
    tty: true
    stdin_open: true
    expose:
      - 9171
    ports:
      - 9171:9171
    image: githubexporter/github-exporter:latest
    environment:
      - REPOS=AlbanAndrieu/nabla-hooks
      - GITHUB_TOKEN=${GITHUB_TOKEN}

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    restart: always

  # https://github.com/RichiH/openweathermap_exporter

  # See https://github.com/jokob-sk/NetAlertX/blob/main/docs/DOCKER_COMPOSE.md
  # docker compose --env-file .env --env-file .env.secrets -f  docker-compose.yml up --force-recreate  netalertx -d
  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "ghcr.io/jokob-sk/netalertx-dev:latest"
    image: "ghcr.io/jokob-sk/netalertx:latest"
    network_mode: "host"
    # network_mode: ${NETALERTX_NETWORK_MODE:-host} # Use host networking for ARP scanning and other services

    read_only: true # Make the container filesystem read-only
    cap_drop: # Drop all capabilities for enhanced security
      - ALL
    cap_add: # Add only the necessary capabilities
      - NET_ADMIN # Required for ARP scanning
      - NET_RAW # Required for raw socket operations
      - NET_BIND_SERVICE # Required to bind to privileged ports (nbtscan)
      - CAP_NET_RAW

    restart: unless-stopped
    volumes:
      # - type: volume # Persistent Docker-managed named volume for config + database
      #   source: netalertx_data
      #   target: /data/netalertx # `/data/config` and `/data/db` live inside this mount
      #   read_only: false

      - type: bind # Bind mount for timezone consistency
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

      # sudo chmod -R 777 data/
      - ./data/db:/data/db
      - ./data/config:/data/config
      - ./data/log:/tmp/log

      # - ${APP_DATA_LOCATION}/netalertx/config:/app/config
      # - ${APP_DATA_LOCATION}/netalertx/db/:/app/db/
      # # (optional) useful for debugging if you have issues setting up the container
      # - ${LOGS_LOCATION}:/app/log
      # # (API: OPTION 1) use for performance

      - type: tmpfs
        target: /app/api
      # (API: OPTION 2) use when debugging issues
      # -  local/path/api:/app/api

    # tmpfs mount consolidates writable state for a read-only container and improves performance
    # uid/gid default to the service user (NETALERTX_UID/GID, default 20211)
    # mode=1700 grants rwx------ permissions to the runtime user only
    tmpfs:
      # Comment out to retain logs between container restarts - this has a server performance impact.
      - "/tmp:uid=${NETALERTX_UID:-20211},gid=${NETALERTX_GID:-20211},mode=1700,rw,noexec,nosuid,nodev,async,noatime,nodiratime"

      # Retain logs - comment out tmpfs /tmp if you want to retain logs between container restarts
      # Please note if you remove the /tmp mount, you must create and maintain sub-folder mounts.
      # - /path/on/host/log:/tmp/log
      # - "/tmp/api:uid=${NETALERTX_UID:-20211},gid=${NETALERTX_GID:-20211},mode=1700,rw,noexec,nosuid,nodev,async,noatime,nodiratime"
      # - "/tmp/nginx:uid=${NETALERTX_UID:-20211},gid=${NETALERTX_GID:-20211},mode=1700,rw,noexec,nosuid,nodev,async,noatime,nodiratime"
      # - "/tmp/run:uid=${NETALERTX_UID:-20211},gid=${NETALERTX_GID:-20211},mode=1700,rw,noexec,nosuid,nodev,async,noatime,nodiratime"

    environment:
      # - TZ=${TZ}
      - TZ=Europe/Paris
      - LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0} # Listen for connections on all interfaces
      - PORT=${PORT:-20211} # Application port
      - GRAPHQL_PORT=${GRAPHQL_PORT:-20212} # GraphQL API port (passed into APP_CONF_OVERRIDE at runtime)
      - APP_DATA_LOCATION=/data
      # - NETALERTX_NETWORK_MODE=host
    # - NETALERTX_DEBUG=${NETALERTX_DEBUG:-0}                 # 0=kill all services and restart if any dies. 1 keeps running dead services.

    # Resource limits to prevent resource exhaustion
    mem_limit: 2048m # Maximum memory usage
    mem_reservation: 1024m # Soft memory limit
    cpu_shares: 512 # Relative CPU weight for CPU contention scenarios
    pids_limit: 512 # Limit the number of processes/threads to prevent fork bombs
    logging:
      driver: "json-file" # Use JSON file logging driver
      options:
        max-size: "10m" # Rotate log files after they reach 10MB
        max-file: "3" # Keep

  portracker:
    image: mostafawahied/portracker:latest
    container_name: portracker
    restart: unless-stopped
    pid: "host" # Required for port detection
    # Required permissions for system ports service namespace access
    cap_add:
      - SYS_PTRACE # Linux hosts: read other PIDs' /proc entries
      - SYS_ADMIN # Docker Desktop: allow namespace access for host ports (required for MacOS)
    security_opt:
      - apparmor:unconfined # Required for system ports
    volumes:
      # Required for data persistence
      - ./portracker-data:/data
      # Required for discovering services running in Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "4999:4999"
    environment:
      # Optional: For enhanced TrueNAS features
      - TRUENAS_API_KEY=${TRUENAS_API_KEY}

  scrutiny-collector:
    restart: unless-stopped
    image: "ghcr.io/analogj/scrutiny:master-collector"
    cap_add:
      - SYS_RAWIO
    volumes:
      - "/run/udev:/run/udev:ro"
    environment:
      COLLECTOR_API_ENDPOINT: "http://172.17.0.24:31054/" # 'http://web:8080'
      COLLECTOR_HOST_ID: "albandrieu" # 'scrutiny-collector-hostname'
      # If true forces the collector to run on startup (cron will be started after the collector completes)
      # see: https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#collector-trigger-on-startup
      COLLECTOR_RUN_STARTUP: false
    # depends_on:
    #   web:
    #     condition: service_healthy
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"

  # docker exec scrutiny-collector /opt/scrutiny/bin/scrutiny-collector-metrics run

  # autoxpose:
  #   image: mostafawahied/autoxpose:latest
  #   ports:
  #     - '4949:3000'
  #   environment:
  #     - SERVER_IP=82.66.4.247
  #     - LAN_IP=172.17.0.57
  #   volumes:
  #     - autoxpose-data:/app/packages/backend/data
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: unless-stopped

volumes: # Persistent volume for configuration and database storage
  netalertx_data:
  autoxpose-data:
  prometheus_data:
    driver: local
