---
services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8

  litellm:
    # image: docker.litellm.ai/berriai/litellm:main-latest # Buggy v1.82.x # main-stable
    image: ghcr.io/berriai/litellm:main-stable # ghcr.io/berriai/litellm:main-stable
    command:
      - "--config"
      - "/app/config.yaml"
      - "--port"
      - "4000"
      # - "--use_v2_migration_resolver"
    environment:
      # DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY}
      LANGFUSE_OTEL_HOST: http://172.17.0.24:3000
      # - REDIS_URL=redis://:XXX@172.17.0.24:30059
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY}
      UI_USERNAME: ${UI_USERNAME}
      UI_PASSWORD: ${UI_PASSWORD}
      STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI
      HEALTH_CHECK_TIMEOUT: 120 # For cold start of qwen
      LITELLM_HEALTH_CHECK_TIMEOUT: 120
      LITELLM_LOG: INFO
    networks:
      - intranet
