---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pyroscope
  title: Grafana Pyroscope
  description: Continuous profiling backend with persistent profiling metadata and profile data.
  labels:
    albandrieu.com/operational-state: active
    albandrieu.com/operational-criticality: medium
    albandrieu.com/business-criticality: medium
    albandrieu.com/bia-scope: direct
  tags:
    - observability
    - profiling
  annotations:
    albandrieu.com/bia-mtpd: P7D
    albandrieu.com/bia-rto: P3D
    albandrieu.com/bia-rpo: P1D
    albandrieu.com/bia-mbco: application-remains-operational-without-continuous-profiling
    albandrieu.com/bia-status: provisional
    albandrieu.com/bia-reviewed-at: "2026-09-22"
    albandrieu.com/bia-impact-operational: low
    albandrieu.com/bia-impact-customer: low
    albandrieu.com/bia-impact-financial: low
    albandrieu.com/bia-impact-legal-regulatory: low
    albandrieu.com/bia-impact-reputation: low
    albandrieu.com/bia-impact-confidentiality: low
    albandrieu.com/bia-impact-integrity: low
    albandrieu.com/bia-impact-privacy: low
    backstage.io/source-location: url:https://github.com/AlbanAndrieu/nabla-compose/tree/master/apps/pyroscope/
    github.com/project-slug: AlbanAndrieu/nabla-compose
spec:
  type: observability
  lifecycle: production
  owner: group:default/nabla-platform
  system: system:default/nabla-homelab
