services:
  litellm:
    # image: docker.litellm.ai/berriai/litellm:main-latest # Buggy v1.82.x # main-stable
    image: ghcr.io/berriai/litellm:main-stable # ghcr.io/berriai/litellm:main-stable
    container_name: litellm
    restart: unless-stopped
    # user: "568:568" # TrueNAS apps user        
    volumes:
      # - /mnt/cpool/litellm/:/app/
      - /mnt/cpool/litellm/config.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
      # - "--port=4000"
      - "--detailed_debug"  
    ports:
      - "4000:4000"
    env_file:
      - /mnt/cpool/litellm/.env.secrets
    environment:
      # - LITELLM_MASTER_KEY=sk_XXX
      # - DATABASE_URL=postgresql://litellm:XXX@172.17.0.24:5432/litellm
      # - UI_USERNAME=nabla 
      # - UI_PASSWORD=XXX 
      - STORE_MODEL_IN_DB="True" # allows adding models to proxy via UI

    healthcheck: # Defines the health check configuration for the container
      test:
        - CMD-SHELL
        - python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:4000/health/liveliness')" # Command to execute for health check
      interval: 30s # Perform health check every 30 seconds
      timeout: 10s # Health check command times out after 10 seconds
      retries: 3 # Retry up to 3 times if health check fails
      start_period: 40s # Wait 40 seconds after container start before beginning health checks
