model_list:

  # ========== Ollama ==========
  #- model_name: llama3.2
  #  litellm_params:
  #    model: "ollama/llama3.2"
  #    api_base: "http://172.17.0.57:11434"
  #    request_timeout: 300
  #    num_ctx: 4096

  - model_name: llama3.2
    litellm_params:
      model: "ollama_chat/llama3.2:3b"
      api_base: "http://172.17.0.24:30068"
      request_timeout: 900
      temperature: 0
      num_ctx: 4096

  # open commit model
  #- model_name: llama3.1
  #  litellm_params:
  #    model: "ollama_chat/llama3.1:8b"
  #    api_base: "http://172.17.0.24:30068"
  #    request_timeout: 900
  #    num_ctx: 2048

  - model_name: llama3.8b
    litellm_params:
      model: "ollama_chat/llama3:8b"
      api_base: "http://172.17.0.24:30068"
      request_timeout: 900
      num_ctx: 2048

  - model_name: deepseek-coder-v2
    litellm_params:
      model: "ollama/deepseek-coder-v2:16b-lite-base-q2_K"
      api_base: "http://172.17.0.24:30068"
      request_timeout: 300
      num_ctx: 2048

  # - model_name: qwen
  #   litellm_params:
  #     model: ollama_chat/qwen3.5:2b
  #     api_base: http://ollama:11434
  #     num_ctx: 4096
  #     temperature: 1.0
  #     top_p: 0.95
  #     extra_body:
  #       top_k: 20
  #       presence_penalty: 1.5

  # texte only for opneweb ui
  - model_name: qwen
    litellm_params:
      model: ollama_chat/qwen3:4b
      api_base: http://172.17.0.57:11434 # using RTX 2060
      # api_base: "http://172.17.0.24:30068"
      extra_body:
        num_ctx: 4096
        temperature: 0.6
        top_p: 0.9
        repeat_penalty: 1.1
        num_predict: 1024
    model_info:
      mode: chat
      supports_function_calling: true
      
  # for opneweb ui chromadb 
  - model_name: embedding
    litellm_params:
      model: ollama/nomic-embed-text
      api_base: "http://172.17.0.24:30068"
    model_info:
      mode: embedding

  - model_name: gemma3
    litellm_params:
      model: "ollama_chat/gemma3"
      api_base: "http://172.17.0.24:30068"
      request_timeout: 900
      num_ctx: 2048
      keep_alive: "30m"

  # reactive resume
  - model_name: rr-json
    litellm_params:
      model: "ollama_chat/qwen2.5:3b" #:14b
      api_base: "http://172.17.0.24:30068"
      temperature: 0
      num_ctx: 8192

general_settings:
  # master_key: sk_XXX
  # database_url: "postgresql://<user>:<password>@<host>:<port>/<dbname>"
  # database_url: postgresql://nabla:XXX@172.17.0.24:5432/litellm
  # disable_cache_on_db_queries: true
  # store_model_in_db: false # change to true or fix : Invalid proxy server token passed ... not found in db
  store_model_in_db: true
  custom_headers:
    forward_headers:
      - X-OpenWebUI-User-Name
      - X-OpenWebUI-User-Id
      - X-OpenWebUI-User-Email
      - X-OpenWebUI-User-Role
      - X-OpenWebUI-Chat-Id
      - X-OpenWebUI-Session
      - X-Session-Id
  user_header_mappings:
    - header_name: X-OpenWebUI-User-Id
      litellm_user_role: internal_user
    - header_name: X-OpenWebUI-User-Email
      litellm_user_role: customer
litellm_settings:
  fallbacks:
    - {"gpt-5.1": ["gpt-4.1", "gpt-4o", "gpt-4.1-mini"]}
    - {"gpt-4.1": ["gpt-4o", "gpt-4.1-mini"]}
    - {"gpt-4o": ["gpt-4.1-mini"]}
    - {"llama3.2": ["gpt-4.1-mini"]}
    - {"gemma3": ["gpt-4.1-mini"]}
    - {"qwen: ["llama3.2"]}
  default_fallbacks: ["llama3.2"]
  cache: true
  cache_params:
    type: redis
    host: redis
    port: 6379
  request_timeout: 600
  num_retries: 1
  # stream: true
  drop_params: true
  # set_verbose: true
  callbacks:
    - langfuse_otel
    - prometheus
  success_callback: ["langfuse_otel"]
  failure_callback: ["langfuse_otel"]
  turn_off_message_logging: false
  langfuse_default_tags:
    - openwebui
    - thiga-ai
    - local-ollama
    - qwen
    - rag
    - assistant-thiga-solution-architect
    - prompt-v1
  prometheus_initialize_budget_metrics: true
router_settings:
  routing_strategy: simple-shuffle
