---
services:
  nginx:
    image: nginx:1-alpine
    container_name: nginx
    restart: unless-stopped    
    environment:
      UID: 1000
      GID: 1000
    ports:
      - 8099:80
    volumes:
      - /mnt/cpool/nginx/html/:/usr/share/nginx/html
    entrypoint:
      - /bin/sh
      - -c
      - |
        deluser nginx
        addgroup -g $${GID} -S nginx
        adduser -S -D -H -u $${UID} -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx
        /docker-entrypoint.sh nginx -g 'daemon off;'
    labels:
      - autoxpose.enable=true # or 'auto' for automatic exposure
      - autoxpose.subdomain=hello # recommended
      - autoxpose.domain=hello.albandrieu.com
      - autoxpose.name=hello
      - autoxpose.scheme=http
      - autoxpose.port=8099
      - "traefik.enable=true"
      - "traefik.http.routers.hello.rule=Host(`hello.int.albandrieu.com`)"
      - "traefik.http.routers.hello.entrypoints=websecure"
      - "traefik.http.routers.hello.tls.certresolver=letsencrypt"
      - "traefik.http.routers.hello.service=hello"
      - "traefik.http.services.hello.loadbalancer.server.scheme=http"      
    networks: ["traefik_network"]      

networks:
  traefik_network:
    external: true
