global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  enabled: true

  standalone:
    enabled: true
    config: |
      ui = true
      disable_mlock = true

      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_disable = 1
      }

      storage "file" {
        path = "/vault/data"
      }

  ha:
    enabled: false

  statefulSet:
    securityContext:
      pod:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      container:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

  dataStorage:
    enabled: true
    size: 2Gi
    mountPath: /vault/data
    storageClass: nabla-truenas-nfs
    accessMode: ReadWriteOnce

  auditStorage:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ui:
  enabled: true
  serviceType: ClusterIP
