---
services:
  traefik:
    image: docker.io/traefik:v3.7.0
    container_name: traefik
    restart: unless-stopped
    env_file:
      - /mnt/cpool/traefik/.env
      - /mnt/cpool/traefik/.env.secrets
    environment:
      - TZ=Europe/Paris
      - CF_API_EMAIL=alban.andrieu@free.fr
    security_opt:
      - no-new-privileges:true

    command:
      # - "--configfile="

      # API / Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--serversTransport.insecureSkipVerify=true" # Or proxmox gives an error 500 due to its own self-signed cert

      #  - "--entrypoints.websecure.http.tls.certResolver=cloudflare"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=int.albandrieu.com" # local.albandrieu.com
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.int.albandrieu.com" # *.local.albandrieu.com
      # - "--providers.file.filename=/etc/traefik/routes.yml"

      - "--providers.file.watch=true"

      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_network"

      # Let's Encrypt / Cloudflare DNS
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/certs/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"

      # - "--certificatesresolvers.cloudflare.acme.email=alban.andrieu@free.fr"
      # # - "--certificatesresolvers.cloudflare.acme.storage=/acme.json"
      # - "--certificatesresolvers.cloudflare.acme.storage=acme.json"
      # - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      # - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      # - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      # - "--certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=30"
      # # - "--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

      # Logging
      # - "--log.level=INFO"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.bufferingsize=100"

      # Metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addentrypointslabels=true"
      - "--metrics.prometheus.addserviceslabels=true"

    ports:
      - "80:80" # Traefik 
      - "443:443" # Traefik    
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/cpool/traefik/:/etc/traefik/  
      # NOK - /mnt/cpool/traefik/routes.yml:/etc/traefik/routes.yml:ro     

    networks: ["traefik_network"]
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.traefik.rule=Host(`traefik.albandrieu.com`)"
      # - "traefik.http.routers.traefik.entrypoints=websecure"
      # - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      # NOK - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_BASIC_AUTH}"

  pihole-dns-sync:
    image: ghcr.io/cajuclc/traefik-pihole-sync:v0.0.1
    container_name: pihole-dns-sync
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/cpool/traefik/:/etc/traefik/
      # - /mnt/cpool/traefik/external-services.yml:/etc/traefik/external-services.yml:ro
      # - /mnt/cpool/traefik/routes.yml:/etc/traefik/routes.yml
    env_file:
      - /mnt/cpool/traefik/.env.secrets      
    environment:
      PIHOLE_URL: http://172.17.0.24:20720
      SKIP_TLS_VERIFY: "true"
      TARGET_IP: 172.17.0.24
      # DOMAIN_SUFFIX: local.albandrieu.com
      DOMAIN_SUFFIX: int.albandrieu.com
      EXTERNAL_SERVICES_FILE: /etc/traefik/external-services.yml
      OUTPUT_FILE: /etc/traefik/routes.yml

networks:
  traefik_network:
    name: traefik_network
    # driver: bridge
    external: true
  ix-dozzle_default: 
    external: true 

volumes:
  acme: {}
