---
services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-fsS",
          "http://localhost:8010/v2/check?language=en-US&text=healthcheck",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.languagetool.rule=Host(`languagetool.int.albandrieu.com`)"
      - "traefik.http.routers.languagetool.entrypoints=websecure"
      - "traefik.http.routers.languagetool.tls.certresolver=letsencrypt"
      - "traefik.http.routers.languagetool.service=languagetool"
      - "traefik.http.services.languagetool.loadbalancer.server.scheme=http"
      - prometheus.scrape=true
      - prometheus.port=8010
    restart: unless-stopped
    ports:
      - 8010:8010 # Using default port from the image
    environment:
      - langtool_languageModel=/ngrams # OPTIONAL: Using ngrams data
      - Java_Xms=512m # OPTIONAL: Setting a minimal Java heap size of 512 mib
      - Java_Xmx=1g # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
      - /mnt/cpool/languagetool/:/ngrams
