input {
  file {
    id => "wazuh-alerts"
    path => "/var/ossec/logs/alerts/alerts.json"
    start_position => "beginning"
    sincedb_path => "/tmp/wazuh-alerts.sincedb"
    codec => "json"
  }
}

output {
  opensearch {
    hosts => ["http://opensearch-security:9200"]
    index => "wazuh-alerts-4.x-%{+YYYY.MM.dd}"
  }
}
