---
services:
  bichon:
    image: rustmailer/bichon:latest
    container_name: bichon
    ports:
      - "15630:15630" # 30313
    volumes:
      - /mnt/cpool/bichon/:/data
    user: "568:568" # TrueNAS apps user
    # user: "1000:1000"
    env_file:
      # - /mnt/cpool/bichon/.env
      - /mnt/cpool/bichon/.env.secrets
    environment:
      BICHON_ROOT_DIR: /data
      BICHON_ENCRYPT_PASSWORD: ${BICHON_ENCRYPTION_PASSWORD}
      BICHON_LOG_LEVEL: info
    networks: ["traefik_network"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bichon.rule=Host(`bichon.albandrieu.com`)"
      - "traefik.http.routers.bichon.entrypoints=websecure"
      - "traefik.http.routers.bichon.tls.certresolver=cloudflare"
      - "traefik.http.routers.bichon.service=bichon"
      - "traefik.http.services.bichon.loadbalancer.server.port=15630"

networks:
  traefik_network:
    external: true
