# pfSense Exporter alert rules (basic templates)
groups:
- name: pfSense
  rules:
    - alert: pfSenseExporterDown
      expr: pfsense_info{host="172.17.0.1"} < 1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: pfSense exporter down
        description: pfSense exporter is not reporting any info (host 172.17.0.1).
