---
configs:
  garage_config:
    file: ./garage.toml

services:
  garage:
    container_name: garage
    image: dxflrs/garage:v2.3.0
    restart: unless-stopped
    configs:
      - source: garage_config
        target: /etc/garage.toml
    env_file:
      - /mnt/cpool/garage/.env.secrets
    #environment:
    #  - GARAGE_RPC_SECRET=${GARAGE_RPC_SECRET}
    #  - GARAGE_ADMIN_TOKEN=${GARAGE_ADMIN_TOKEN}
    volumes:
      - /mnt/cpool/garage/meta:/var/lib/garage/meta
      - /mnt/cpool/garage/data:/var/lib/garage/data
      - /mnt/cpool/garage/garage_admin_token:/run/secrets/garage_admin_token:ro
    ports:
      - "3900:3900"
      - "3901:3901"   # RPC Garage obligatoire
      - "3903:3903"   # Admin API
    networks: ["traefik_network"]
    labels:
      - "traefik.enable=true"
      # S3 API
      - "traefik.http.routers.garage-s3.rule=Host(`s3.int.albandrieu.com`) || HostRegexp(`{subdomain:.+}.s3.int.albandrieu.com`)"
      - "traefik.http.routers.garage-s3.entrypoints=websecure"
      - "traefik.http.routers.garage-s3.tls.certresolver=letsencrypt"
      - "traefik.http.routers.garage-s3.service=garage-s3"
      - "traefik.http.services.garage-s3.loadbalancer.server.scheme=http"
      # - "traefik.http.services.garage-s3.loadbalancer.server.port=3900"
      # Admin API
      - "traefik.http.routers.garage-admin.rule=Host(`garage-admin.int.albandrieu.com`)"
      - "traefik.http.routers.garage-admin.entrypoints=websecure"
      - "traefik.http.routers.garage-admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.garage-admin.service=garage-admin"
      - "traefik.http.services.garage-admin.loadbalancer.server.scheme=http"
      - "traefik.http.services.garage-admin.loadbalancer.server.port=3903"

  webui:
    container_name: garage-webui
    image: khairul169/garage-webui:1.1.0
    restart: unless-stopped
    configs:
      - source: garage_config
        target: /etc/garage.toml
    ports:
      - "3909:3909"
    volumes:
      - /mnt/cpool/garage/garage_admin_token:/run/secrets/garage_admin_token:ro
    environment:
      API_BASE_URL: "http://172.17.0.24:3903"
      API_ADMIN_KEY: "${GARAGE_ADMIN_TOKEN}"
      S3_ENDPOINT_URL: "http://172.17.0.24:3900"
      # AUTH_USER_PASS: "${GARAGE_WEBUI_ADMIN_PASS}"
    networks: ["traefik_network"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.garage-webui.rule=Host(`garage.int.albandrieu.com`)"
      - "traefik.http.routers.garage-webui.entrypoints=websecure"
      - "traefik.http.routers.garage-webui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.garage-webui.service=garage-webui"
      - "traefik.http.services.garage-webui.loadbalancer.server.scheme=http"
      # - "traefik.http.services.garage-webui.loadbalancer.server.port=3909"

networks:
  traefik_network:
    external: true
