---
services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      # - 9080:8080
      - 9443:8443
    environment:
      - PUBLIC_DNS=${PUBLIC_DNS:-drawio.albandrieu.com}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawio.rule=Host(`drawio.int.albandrieu.com`)"
      - "traefik.http.routers.drawio.entrypoints=websecure"
      # - "traefik.http.routers.drawio.tls.certresolver=cloudflare"
      - "traefik.http.routers.drawio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.drawio.service=drawio"
      - "traefik.http.services.drawio.loadbalancer.server.port=9443"
