---
services:
  clickhouse:
    image: docker.io/clickhouse/clickhouse-server
    restart: unless-stopped
    user: "568:568" # TrueNAS apps user
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-clickhouse}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-clickhouse} # CHANGEME
    volumes:
      - /mnt/cpool/clickhouse/:/var/lib/clickhouse
      # - /mnt/cpool/clickhouse/logs:/var/log/clickhouse-server
      - /mnt/cpool/logs/clickhouse-server/:/var/log/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s
