---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: http://172.17.0.24:9009/api/v1/push

scrape_configs:
  - job_name: scrutiny
    static_configs:
      - targets:
          - 172.17.0.24:8080

  - job_name: pfsense_exporter
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
          - 172.17.0.1:10443
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: __address__
        replacement: 172.17.0.24:9945
      - source_labels:
          - __param_target
        target_label: instance

  - job_name: crowdsec
    static_configs:
      - targets:
          - 172.17.0.24:6060

  - job_name: haproxy
    static_configs:
      - targets:
          - 172.17.0.24:9101

  - job_name: sybase
    static_configs:
      - targets:
          - 172.17.0.24:9113

  - job_name: clickhouse
    metrics_path: /metrics
    static_configs:
      - targets:
          - 172.17.0.24:9363

  - job_name: opensearch
    static_configs:
      - targets:
          - 172.17.0.24:9114

  - job_name: opensearch-security
    static_configs:
      - targets:
          - 172.17.0.24:9115
