---
services:
  redis:
    image: docker.io/redis:8.8.0
    # image: redis:7-alpine
    # image: registry.community.greenbone.net/community/redis-server
    container_name: redis
    x-nabla:
      id: redis
      name: Redis
      kind: cache
      category: data
      runtime:
        provider: truenas-app
        containerService: redis
    restart: unless-stopped
    # CHANGEME: row below to secure redis password
    command: >
      --requirepass ${REDIS_AUTH:-myredissecret}
      --maxmemory-policy noeviction
    ports:
      - 30059:6379
    volumes:
      - /mnt/cpool/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      intranet:
        aliases:
          - redis

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    restart: unless-stopped
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: ${REDIS_AUTH:-myredissecret}
    ports:
      - 9121:9121
    depends_on:
      - redis
    networks:
      - intranet

networks:
  intranet:
    external: true
    name: intranet
