---
name: Lint using super-linter

on: [pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: Lint using super-linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@v8.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_ISORT: false
          FILTER_REGEX_EXCLUDE: ^(anything-llm|langfuse|litellm|n8n|pgwatch|plumber-platform|reactive|sentry|temporal)/
