---
services:
  sentry-web:
    image: getsentry/sentry:latest
    container_name: sentry-web
    env_file:
      - /mnt/cpool/compose/nabla-compose/apps/sentry/.env
    environment:
      # SENTRY_SECRET_KEY: "XXX"
      SENTRY_REDIS_HOST: 172.17.0.24
      SENTRY_REDIS_PORT: 30059      
      # SENTRY_REDIS_PASSWORD: XXX
      # SENTRY_REDIS_URL: "redis://default:XXX@172.17.0.24:30059/0"
      SENTRY_POSTGRES_HOST: 172.17.0.24
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: sentry
      # SENTRY_DB_PASSWORD: XXX
      SENTRY_DB_NAME: sentry
      # For ClickHouse
      SENTRY_CLICKHOUSE_HOST: 172.17.0.24
      SENTRY_CLICKHOUSE_PORT: 8123
      SENTRY_CLICKHOUSE_USER: clickhouse
      # SENTRY_CLICKHOUSE_PASSWORD: clickhouse
      # Add SENTRY_FILESTORE_* for Minio if you wish
    ports:
      - 9005:9000
    restart: unless-stopped
    networks:
      - default
      - traefik_network

  sentry-worker:
    image: getsentry/sentry:latest
    container_name: sentry-worker
    command: run worker
    env_file:
      - /mnt/cpool/compose/nabla-compose/apps/sentry/.env    
    environment:
      # SENTRY_SECRET_KEY: "XXX"
      SENTRY_REDIS_HOST: 172.17.0.24
      SENTRY_REDIS_PORT: 30059
      # SENTRY_REDIS_PASSWORD: XXX
      # SENTRY_REDIS_URL: "redis://default:XXX@172.17.0.24:30059/0"
      SENTRY_POSTGRES_HOST: 172.17.0.24
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: sentry
      # SENTRY_DB_PASSWORD: XXX
      SENTRY_DB_NAME: sentry
      SENTRY_CLICKHOUSE_HOST: 172.17.0.24
      SENTRY_CLICKHOUSE_PORT: 8123
      SENTRY_CLICKHOUSE_USER: clickhouse
      # SENTRY_CLICKHOUSE_PASSWORD: clickhouse
    restart: unless-stopped
    networks:
      - default
      - traefik_network

  sentry-cron:
    image: getsentry/sentry:latest
    container_name: sentry-cron
    command: run cron
    env_file:
      - /mnt/cpool/compose/nabla-compose/apps/sentry/.env    
    environment:
      # SENTRY_SECRET_KEY: "XXX"
      SENTRY_REDIS_HOST: 172.17.0.24
      SENTRY_REDIS_PORT: 30059
      # SENTRY_REDIS_PASSWORD: XXX
      # SENTRY_REDIS_URL: "redis://default:XXX@172.17.0.24:30059/0"
      SENTRY_POSTGRES_HOST: 172.17.0.24
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: sentry
      # SENTRY_DB_PASSWORD: XXX
      SENTRY_DB_NAME: sentry
      SENTRY_CLICKHOUSE_HOST: 172.17.0.24
      SENTRY_CLICKHOUSE_PORT: 8123
      SENTRY_CLICKHOUSE_USER: clickhouse
      # SENTRY_CLICKHOUSE_PASSWORD: clickhouse
    restart: unless-stopped
    networks:
      - default
      - traefik_network

networks:
  secrets-backend:
    external: true
  traefik_network:
    external: true
#volumes:
#  sentry_redis_data:
#  sentry_postgres_data:
#  sentry_clickhouse_data:
